version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - db_app
  app:
    depends_on:
      - mysqldb
    image: book-store
    restart: on-failure
    container_name: app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DB?serverTimeZone=UTC",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD", 
        "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect"                     
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - db_app
networks:
  db_app:
    driver: bridge
